In [13]:
import pandas as pd 
fifa=pd.read_csv(r"C:\Users\Amin\Downloads\fifa19.csv")
fifa.head(12)

    Unnamed: 0      ID               Name  Age  ... GKKicking GKPositioning GKReflexes  Release Clause
0            0  158023           L. Messi   31  ...      15.0          14.0        8.0         €226.5M
1            1   20801  Cristiano Ronaldo   33  ...      15.0          14.0       11.0         €127.1M
2            2  190871          Neymar Jr   26  ...      15.0          15.0       11.0         €228.1M
3            3  193080             De Gea   27  ...      87.0          88.0       94.0         €138.6M
4            4  192985       K. De Bruyne   27  ...       5.0          10.0       13.0         €196.4M
5            5  183277          E. Hazard   27  ...       6.0           8.0        8.0         €172.1M
6            6  177003          L. Modrić   32  ...       7.0          14.0        9.0         €137.4M
7            7  176580          L. Suárez   31  ...      31.0          33.0       37.0           €164M
8            8  155862       Sergio Ramos   32  ...       9.0           7.0       11.0         €104.6M
9            9  200389           J. Oblak   25  ...      78.0          88.0       89.0         €144.5M
10          10  188545     R. Lewandowski   29  ...      12.0           8.0       10.0         €127.1M
11          11  182521           T. Kroos   28  ...      13.0           7.0       10.0         €156.8M

[12 rows x 89 columns]

In [14]:
fifa.info()
len(fifa)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18207 non-null  int64
 1   ID                        18207 non-null  int64
 2   Name                      18207 non-null  object
 3   Age                       18207 non-null  int64
 4   Photo                     18207 non-null  object
 5   Nationality               18207 non-null  object
 6   Flag                      18207 non-null  object
 7   Overall                   18207 non-null  int64
 8   Potential                 18207 non-null  int64
 9   Club                      17966 non-null  object
 10  Club Logo                 18207 non-null  object
 11  Value                     18207 non-null  object
 12  Wage                      18207 non-null  object
 13  Special                   18207 non-null  int64
 14  Preferred Foot            18159 non-null  object
 15  International Reputation  18159 non-null  float64
 16  Weak Foot                 18159 non-null  float64
 17  Skill Moves               18159 non-null  float64
 18  Work Rate                 18159 non-null  object
 19  Body Type                 18159 non-null  object
 20  Real Face                 18159 non-null  object
 21  Position                  18147 non-null  object
 22  Jersey Number             18147 non-null  float64
 23  Joined                    16654 non-null  object
 24  Loaned From               1264 non-null   object
 25  Contract Valid Until      17918 non-null  object
 26  Height                    18159 non-null  object
 27  Weight                    18159 non-null  object
 28  LS                        16122 non-null  object
 29  ST                        16122 non-null  object
 30  RS                        16122 non-null  object
 31  LW                        16122 non-null  object
 32  LF                        16122 non-null  object
 33  CF                        16122 non-null  object
 34  RF                        16122 non-null  object
 35  RW                        16122 non-null  object
 36  LAM                       16122 non-null  object
 37  CAM                       16122 non-null  object
 38  RAM                       16122 non-null  object
 39  LM                        16122 non-null  object
 40  LCM                       16122 non-null  object
 41  CM                        16122 non-null  object
 42  RCM                       16122 non-null  object
 43  RM                        16122 non-null  object
 44  LWB                       16122 non-null  object
 45  LDM                       16122 non-null  object
 46  CDM                       16122 non-null  object
 47  RDM                       16122 non-null  object
 48  RWB                       16122 non-null  object
 49  LB                        16122 non-null  object
 50  LCB                       16122 non-null  object
 51  CB                        16122 non-null  object
 52  RCB                       16122 non-null  object
 53  RB                        16122 non-null  object
 54  Crossing                  18159 non-null  float64
 55  Finishing                 18159 non-null  float64
 56  HeadingAccuracy           18159 non-null  float64
 57  ShortPassing              18159 non-null  float64
 58  Volleys                   18159 non-null  float64
 59  Dribbling                 18159 non-null  float64
 60  Curve                     18159 non-null  float64
 61  FKAccuracy                18159 non-null  float64
 62  LongPassing               18159 non-null  float64
 63  BallControl               18159 non-null  float64
 64  Acceleration              18159 non-null  float64
 65  SprintSpeed               18159 non-null  float64
 66  Agility                   18159 non-null  float64
 67  Reactions                 18159 non-null  float64
 68  Balance                   18159 non-null  float64
 69  ShotPower                 18159 non-null  float64
 70  Jumping                   18159 non-null  float64
 71  Stamina                   18159 non-null  float64
 72  Strength                  18159 non-null  float64
 73  LongShots                 18159 non-null  float64
 74  Aggression                18159 non-null  float64
 75  Interceptions             18159 non-null  float64
 76  Positioning               18159 non-null  float64
 77  Vision                    18159 non-null  float64
 78  Penalties                 18159 non-null  float64
 79  Composure                 18159 non-null  float64
 80  Marking                   18159 non-null  float64
 81  StandingTackle            18159 non-null  float64
 82  SlidingTackle             18159 non-null  float64
 83  GKDiving                  18159 non-null  float64
 84  GKHandling                18159 non-null  float64
 85  GKKicking                 18159 non-null  float64
 86  GKPositioning             18159 non-null  float64
 87  GKReflexes                18159 non-null  float64
 88  Release Clause            16643 non-null  object
dtypes: float64(38), int64(6), object(45)
memory usage: 12.4+ MB

18207

In [15]:
print(fifa.columns)

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [17]:
fifa.iloc[4999]

Unnamed: 0                                                  4999
ID                                                        202050
Name                                                    T. Bruns
Age                                                           26
Photo             https://cdn.sofifa.org/players/4/19/202050.png
                                       ...
GKHandling                                                  11.0
GKKicking                                                   13.0
GKPositioning                                               14.0
GKReflexes                                                   9.0
Release Clause                                             €3.4M
Name: 4999, Length: 89, dtype: object

In [18]:
fifa['ID']

0        158023
1         20801
2        190871
3        193080
4        192985
          ...
18202    238813
18203    243165
18204    241638
18205    246268
18206    246269
Name: ID, Length: 18207, dtype: int64

In [19]:
fifa.sort_values(by=['Club','Name'])

       Unnamed: 0      ID          Name  Age  ... GKKicking GKPositioning GKReflexes  Release Clause
7657         7657  238594        A. Dej   26  ...      14.0          10.0       13.0           €1.5M
11244       11244  244280       A. Fein   19  ...      12.0          12.0        6.0             NaN
7184         7184  213644      A. Geipl   26  ...       8.0          12.0        8.0           €1.5M
6917         6917  238666    A. Nandzik   25  ...       6.0          14.0       10.0           €1.5M
12363       12363  238667     A. Odabas   24  ...       6.0           7.0        8.0           €744K
...           ...     ...           ...  ...  ...       ...           ...        ...             ...
9373         9373  246406    X. Arreaga   23  ...       8.0          11.0        8.0             NaN
3037         3037  207797     Y. Banana   26  ...       7.0           7.0        6.0             NaN
1602         1602  216335  Y. Gazinskiy   28  ...      11.0          15.0        9.0             NaN
3710         3710  245665   Y. Ouattara   34  ...      15.0          13.0        8.0             NaN
4667         4667  223208     Z. Kalmár   23  ...      12.0          15.0        6.0             NaN

[18207 rows x 89 columns]

In [20]:
fifa[fifa['Overall']>90]

   Unnamed: 0      ID               Name  Age  ... GKKicking GKPositioning GKReflexes  Release Clause
0           0  158023           L. Messi   31  ...      15.0          14.0        8.0         €226.5M
1           1   20801  Cristiano Ronaldo   33  ...      15.0          14.0       11.0         €127.1M
2           2  190871          Neymar Jr   26  ...      15.0          15.0       11.0         €228.1M
3           3  193080             De Gea   27  ...      87.0          88.0       94.0         €138.6M
4           4  192985       K. De Bruyne   27  ...       5.0          10.0       13.0         €196.4M
5           5  183277          E. Hazard   27  ...       6.0           8.0        8.0         €172.1M
6           6  177003          L. Modrić   32  ...       7.0          14.0        9.0         €137.4M
7           7  176580          L. Suárez   31  ...      31.0          33.0       37.0           €164M
8           8  155862       Sergio Ramos   32  ...       9.0           7.0       11.0         €104.6M

[9 rows x 89 columns]

In [22]:
fifa=fifa.drop(columns=['Unnamed: 0'])

In [23]:
fifa['Position'].nunique()

27

In [24]:
fifa.isnull().sum()

ID                   0
Name                 0
Age                  0
Photo                0
Nationality          0
                  ...
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 88, dtype: int64

In [25]:
fifa['Release Clause']=fifa['Release Clause'].fillna('unknown')

In [26]:
fifa['Age'].mean()

np.float64(25.122205745043114)

In [27]:
fifa['ShotPower'].max()

95.0

In [28]:
fifa[fifa['ShotPower']==fifa['ShotPower'].max()]

      ID               Name  Age  ... GKPositioning GKReflexes Release Clause
1  20801  Cristiano Ronaldo   33  ...          14.0       11.0        €127.1M

[1 rows x 88 columns]

In [29]:
fifa.describe()

                  ID           Age       Overall     Potential  ...    GKHandling     GKKicking  GKPositioning    GKReflexes
count   18207.000000  18207.000000  18207.000000  18207.000000  ...  18159.000000  18159.000000   18159.000000  18159.000000
mean   214298.338606     25.122206     66.238699     71.307299  ...     16.391596     16.232061      16.388898     16.710887
std     29965.244204      4.669943      6.908930      6.136496  ...     16.906900     16.502864      17.034669     17.955119
min        16.000000     16.000000     46.000000     48.000000  ...      1.000000      1.000000       1.000000      1.000000
25%    200315.500000     21.000000     62.000000     67.000000  ...      8.000000      8.000000       8.000000      8.000000
50%    221759.000000     25.000000     66.000000     71.000000  ...     11.000000     11.000000      11.000000     11.000000
75%    236529.500000     28.000000     71.000000     75.000000  ...     14.000000     14.000000      14.000000     14.000000
max    246620.000000     45.000000     94.000000     95.000000  ...     92.000000     91.000000      90.000000     94.000000

[8 rows x 43 columns]